import Vue from "vue";
import {
  Aside,
  Button,
  Breadcrumb,
  BreadcrumbItem,
  Card,
  Container,
  Cascader,
  Dialog,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  DatePicker,
  Form,
  FormItem,
  Header,
  Input,
  Tabs,
  Row,
  Col,
  Main,
  Menu,
  Message,
  MessageBox,
  Submenu,
  MenuItemGroup,
  MenuItem,
  Divider,
  Pagination,
  Option,
  Select,
  Switch,
  Tag,
  Tree,
  Radio,
  Table,
  TableColumn,
  Tooltip,
  Image,
  Upload
} from "element-ui";

Vue.use(Aside)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Button)
Vue.use(Card)
Vue.use(Container)
Vue.use(Cascader)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Header)
Vue.use(Input)
Vue.use(DatePicker)
Vue.use(Dialog)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Tabs)
Vue.use(Row)
Vue.use(Col)
Vue.use(Main)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(MenuItem)
Vue.use(Divider)
Vue.use(Select)
Vue.use(Switch)
Vue.use(Tag)
Vue.use(Tree)
Vue.use(Radio)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Tooltip)
Vue.use(Option)
Vue.use(Pagination)
Vue.use(Image)
Vue.use(Upload)

Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
